/*
 * mission_tables.c — Stub mission configuration tables
 *
 * In a full cFS build these are generated by CMake from the mission
 * configuration.  Here we provide minimal tables so that
 * target_config.c can link, plus the platform config arrays that
 * cFE needs at runtime (mem-pool block sizes).
 */

#include "target_config.h"
#include "cfe_config_ids.h"
#include "cfe_config_set.h"
#include "cfe_config_api_typedefs.h"

/* Mission name & config strings */
const char CFE_MISSION_NAME[]   = "esp32-cfs";
const char CFE_MISSION_CONFIG[] = "default";

/* Empty module lists */
CFE_StaticModuleLoadEntry_t CFE_PSP_MODULE_LIST[] = {{NULL, NULL}};
CFE_ConfigName_t            CFE_CORE_MODULE_LIST[] = {{NULL}};
CFE_ConfigName_t            CFE_STATIC_APP_LIST[] = {{NULL}};

/* Empty key-value tables */
CFE_ConfigKeyValue_t CFE_BUILD_ENV_TABLE[] = {{NULL, NULL}};
CFE_ConfigKeyValue_t CFE_MODULE_VERSION_TABLE[] = {{NULL, NULL}};

/*
 * Default memory-pool block-size arrays.
 * These are normally generated by the cFE platform-config tool.
 */
static const size_t SB_MEM_BLOCK_SIZES[] = {
    8, 16, 20, 36, 64, 96, 128, 160, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768
};

static const size_t ES_MEM_BLOCK_SIZES[] = {
    8, 16, 32, 48, 64, 96, 128, 160, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768
};

static const size_t ES_CDS_MEM_BLOCK_SIZES[] = {
    8, 16, 32, 48, 64, 96, 128, 160, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768
};

static const CFE_Config_ArrayValue_t SB_MEM_BLOCK_ARRAY = {
    sizeof(SB_MEM_BLOCK_SIZES) / sizeof(SB_MEM_BLOCK_SIZES[0]),
    SB_MEM_BLOCK_SIZES
};

static const CFE_Config_ArrayValue_t ES_MEM_BLOCK_ARRAY = {
    sizeof(ES_MEM_BLOCK_SIZES) / sizeof(ES_MEM_BLOCK_SIZES[0]),
    ES_MEM_BLOCK_SIZES
};

static const CFE_Config_ArrayValue_t ES_CDS_MEM_BLOCK_ARRAY = {
    sizeof(ES_CDS_MEM_BLOCK_SIZES) / sizeof(ES_CDS_MEM_BLOCK_SIZES[0]),
    ES_CDS_MEM_BLOCK_SIZES
};

/* Stub for platform config info normally generated by CMake */
void CFE_Config_SetupPlatformConfigInfo(void)
{
    CFE_Config_SetArrayValue(CFE_CONFIGID_PLATFORM_SB_MEM_BLOCK_SIZE, &SB_MEM_BLOCK_ARRAY);
    CFE_Config_SetArrayValue(CFE_CONFIGID_PLATFORM_ES_MEM_BLOCK_SIZE, &ES_MEM_BLOCK_ARRAY);
    CFE_Config_SetArrayValue(CFE_CONFIGID_PLATFORM_ES_CDS_MEM_BLOCK_SIZE, &ES_CDS_MEM_BLOCK_ARRAY);
}
